#!/bin/bash
# script: composer
# Purpose: execute a composer command inside the container

args="$@"
command="composer $args"
echo "$command"

CONTAINER=laravel-app
USER=devuser

docker exec -it $CONTAINER bash -c "sudo -u $USER /bin/bash -c \"$command\""