#!/bin/bash
# script: container
# Purpose: open a bash shell inside the container

# Load environment variables from the .env file
if [ -f .env ]; then
  export $(grep -v -E '^#|^UID=' .env | xargs)
fi

# Define constants
CONTAINER=${PROJECT_NAME}-app

# Execute the command
docker exec -it $CONTAINER bash -c "sudo -u devuser /bin/bash"