services:
  app:
    build:
      context: .
      args:
        uid: ${UID}
        TZ: ${DB_TZ}
    image: laravel-apache/dev:latest
    container_name: laravel-app
    volumes:
      - '$PWD/app:/var/www/html'
      - '$PWD/config/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - '${APP_PORT}:80'
    environment:
      - TZ=${DB_TZ}
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - '$PWD/db:/var/lib/mysql'
      - '$PWD/config/conf.d:/etc/mysql/conf.d'
    environment:
      TZ: ${DB_TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 512M
      TZ: ${DB_TZ}
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - backend

networks:
  backend:
    name: backend_network
