#!/bin/bash
# script: fix-permissions
# Purpose: fix storage and bootstrap/cache permissions inside the container

# Load environment variables from the .env file
if [ -f .env ]; then
  export $(grep -v -E '^#|^UID=' .env | xargs)
fi

# Define constants
CONTAINER=${PROJECT_NAME}-app
APP_PATH=/var/www/html

# Execute the command
docker exec -it $CONTAINER bash -c "chown -R devuser:www-data $APP_PATH/storage $APP_PATH/bootstrap/cache && chmod -R 775 $APP_PATH/storage $APP_PATH/bootstrap/cache"
echo "Permissions for storage and bootstrap/cache fixed!"
