#!/bin/bash
# script: php-artisan
# Purpose: execute a php artisan command inside the container

args="$@"
command="php artisan $args"
echo "$command"

CONTAINER=laravel-app
USER=devuser

docker exec -it $CONTAINER bash -c "sudo -u $USER /bin/bash -c \"$command\""