#!/bin/bash
# script: php-artisan
# Purpose: execute a php artisan command inside the container

# Load environment variables from the .env file
if [ -f .env ]; then
  export $(grep -v -E '^#|^UID=' .env | xargs)
fi

# Get the command line arguments
args="$@"
command="php artisan $args"
echo "$command"

# Define constants
CONTAINER=${PROJECT_NAME}-app

# Execute the command
docker exec -it $CONTAINER bash -c "sudo -u devuser /bin/bash -c \"$command\""