#!/bin/bash
# script: phpunit
# Purpose: execute a phpunit command inside the container

args="$@"
command="vendor/bin/phpunit $args"
echo "$command"

CONTAINER=laravel-app
USER=devuser

docker exec -it $CONTAINER bash -c "sudo -u $USER /bin/bash -c \"$command\""